    <script type="text/javascript" src="/scripts/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="/scripts/layer.js"></script>
    <script type="text/javascript" src="/scripts/pj_reg_ajax.js"></script>
    <script type='text/javascript' src='/scripts/pj_loadPmAndsmg.js'></script>
    <script type='text/javascript' src='/scripts/js.KinerCode.js'></script>
    <script type='text/javascript' src='/scripts/pj_authcode.js'></script> 
    <script type='text/javascript' src='/scripts/pj_forgetpw.js'></script>
    <script type='text/javascript' src='/scripts/pj_constant.js'></script>
    <script type="text/javascript" src="/scripts/jquery-jtemplates.js"></script>